name: Publish Package
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
concurrency:
  group: "pages"
  cancel-in-progress: false
env:
  BUILD_PATH: docs
permissions:
  issues: write
  contents: write
  packages: write
  pull-requests: write
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
      - run: npm ci
      - run: npm run build -w @awesome-algorand/core-fetch
      - run: node ./bin/publisher.js
        env:
          NPM_CONFIG_REGISTRY: 'https://npm.pkg.github.com'
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit
        run: |
          git diff --quiet && git diff --staged --quiet || git commit -am "🔖 Release ${{ github.sha }}"
          git push